CREATE TABLE QUESTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_TEXT VARCHAR(255) NOT NULL,
    OPTION_A VARCHAR(100),
    OPTION_B VARCHAR(100),
    OPTION_C VARCHAR(100),
    OPTION_D VARCHAR(100),
    CORRECT_ANSWER CHAR(1)
);


INSERT INTO QUESTION (QUESTION_TEXT, OPTION_A, OPTION_B, OPTION_C, OPTION_D, CORRECT_ANSWER)
VALUES ('What is 2 + 2?', '3', '4', '5', '6', 'B'),
       ('What is the capital of France?', 'Paris', 'London', 'Rome', 'Berlin', 'A');
